version: "2"

networks:
    platform:
      external:
          name: spidplatform_default
services:
  paymock:
    build: .
    ports:
      - 8092:80
    networks:
      - platform
      - default
  dba:
    image: mysql:5.6
    ports:
      - 3307:3306
    volumes:
            - ./src/main/docker/data/mysql/create.sql:/docker-entrypoint-initdb.d/create.sql
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=paymockdb
      - MYSQL_USER=paymockuser
      - MYSQL_PASSWORD=root


#docker run --name demo-mysql
#-e MYSQL_ROOT_PASSWORD=demo
#-e MYSQL_DATABASE=demo
#-e MYSQL_USER=demo_user
#-e MYSQL_PASSWORD=demo_pass
#-p 3307:3306
#-d mysql:5.6