server:
    port: 80

spring:
    jpa:
        database: MYSQL

    datasource:
        url: jdbc:mysql://dba:3306/paymockdb
        username: root
        password: root
        driver-class-name: com.mysql.jdbc.Driver