server:
    port: 80

spring:
    jpa:
        database: MYSQL
        hibernate:
            ddl-auto: validate

    datasource:
        url: jdbc:mysql://db:3307/demo
        username: paymockuser
        password: root
        driver-class-name: com.mysql.jdbc.Driver